# Generated by Django 3.0.4 on 2020-04-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200414_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='User',
        ),
    ]
