# Generated by Django 3.0.4 on 2020-04-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200414_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Forms',
        ),
        migrations.AlterModelTable(
            name='forms',
            table='form',
        ),
    ]
