# Generated by Django 3.0.4 on 2020-04-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200415_1333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forms',
            table=None,
        ),
    ]
