# Generated by Django 3.0.4 on 2020-04-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200415_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='password',
        ),
    ]
