# Generated by Django 3.0.6 on 2020-05-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sstudent',
        ),
    ]
